// Generated using Sourcery 2.0.2 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
import Foundation
import Components

// swiftlint:disable all
// This file is automatically generated by Sourcery

extension BenefitButtonComponent {
    public static var documentation: ComponentDocumentation {
        .init(
            name: "BenefitButtonComponent",
            kind: BenefitButtonComponent.kind,
            variables: [
                .init(
                    name: "text",
                    type: "String",
                    documentation: [],
                    defaultValue: ""
                ),
                .init(
                    name: "style",
                    type: "String",
                    documentation: [],
                    defaultValue: "\"black\""
                ),
                .init(
                    name: "cornerRadius",
                    type: "CGFloat",
                    documentation: [],
                    defaultValue: "12"
                ),
                .init(
                    name: "fullWidth",
                    type: "Bool",
                    documentation: [],
                    defaultValue: "true"
                ),
            ]
        )
    }
}
extension BenefitCardComponent {
    public static var documentation: ComponentDocumentation {
        .init(
            name: "BenefitCardComponent",
            kind: BenefitCardComponent.kind,
            variables: [
                .init(
                    name: "backgroundImage",
                    type: "String",
                    documentation: [],
                    defaultValue: "\"benefit_climate\""
                ),
                .init(
                    name: "title",
                    type: "String",
                    documentation: [],
                    defaultValue: ""
                ),
                .init(
                    name: "description",
                    type: "String",
                    documentation: [],
                    defaultValue: ""
                ),
                .init(
                    name: "badgeText",
                    type: "String",
                    documentation: [],
                    defaultValue: ""
                ),
                .init(
                    name: "statusText",
                    type: "String",
                    documentation: [],
                    defaultValue: "\"Aktiv\""
                ),
                .init(
                    name: "isActive",
                    type: "Bool",
                    documentation: [],
                    defaultValue: "true"
                ),
                .init(
                    name: "cornerRadius",
                    type: "CGFloat",
                    documentation: [],
                    defaultValue: "16"
                ),
            ]
        )
    }
}
extension ButtonComponent {
    public static var documentation: ComponentDocumentation {
        .init(
            name: "ButtonComponent",
            kind: ButtonComponent.kind,
            variables: [
                .init(
                    name: "title",
                    type: "String",
                    documentation: [],
                    defaultValue: ""
                ),
                .init(
                    name: "style",
                    type: "ButtonStyle",
                    documentation: [],
                    defaultValue: ""
                ),
                .init(
                    name: "isEnabled",
                    type: "Bool",
                    documentation: [],
                    defaultValue: ""
                ),
                .init(
                    name: "isLoading",
                    type: "Bool",
                    documentation: [],
                    defaultValue: ""
                ),
            ]
        )
    }
}
extension LanguageSwitcherComponent {
    public static var documentation: ComponentDocumentation {
        .init(
            name: "LanguageSwitcherComponent",
            kind: LanguageSwitcherComponent.kind,
            variables: [
                .init(
                    name: "selectedLanguageCode",
                    type: "String",
                    documentation: [],
                    defaultValue: "\"DE\""
                ),
                .init(
                    name: "languageRegions",
                    type: "LanguageRegion",
                    documentation: [],
                    defaultValue: ".all"
                ),
                .init(
                    name: "specificLanguageCodes",
                    type: "Set<String>",
                    documentation: [],
                    defaultValue: "[]"
                ),
                .init(
                    name: "showSearch",
                    type: "Bool",
                    documentation: [],
                    defaultValue: "true"
                ),
                .init(
                    name: "size",
                    type: "CGFloat",
                    documentation: [],
                    defaultValue: "32"
                ),
            ]
        )
    }
}
// swiftlint:enable all
