// Generated using Sourcery 2.0.2 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
import Foundation
import Components

// swiftlint:disable all
// This file is automatically generated by Sourcery

public func registerComponents(in registry: ComponentsRegistry) {
    BenefitButtonComponent.register(in: registry)
    BenefitCardComponent.register(in: registry)
    ButtonComponent.register(in: registry)
    LanguageSwitcherComponent.register(in: registry)
}

public func registerDocumentation() {
    ComponentDocumentation.all.append(BenefitButtonComponent.documentation)
    ComponentDocumentation.all.append(BenefitCardComponent.documentation)
    ComponentDocumentation.all.append(ButtonComponent.documentation)
    ComponentDocumentation.all.append(LanguageSwitcherComponent.documentation)
}

// swiftlint:enable all
