// Generated using Sourcery 2.0.2 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
import Foundation
// swiftlint:disable all
// This file is automatically generated by Sourcery

extension BenefitButtonComponent.Data {
    public enum CodingKeys: String, CodingKey {
        case text = "text"
        case style = "style"
        case cornerRadius = "corner_radius"
        case fullWidth = "full_width"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: BenefitButtonComponent.Data.CodingKeys.self)
        self.text = try container.decode(String.self, forKey: .text)
        self.style = try container.decodeIfPresent(String.self, forKey: .style) ?? "black"
        self.cornerRadius = try container.decodeIfPresent(CGFloat.self, forKey: .cornerRadius) ?? 12
        self.fullWidth = try container.decodeIfPresent(Bool.self, forKey: .fullWidth) ?? true
    }
}
extension BenefitCardComponent.Data {
    public enum CodingKeys: String, CodingKey {
        case backgroundImage = "background_image"
        case title = "title"
        case description = "description"
        case badgeText = "badge_text"
        case statusText = "status_text"
        case isActive = "is_active"
        case cornerRadius = "corner_radius"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: BenefitCardComponent.Data.CodingKeys.self)
        self.backgroundImage = try container.decodeIfPresent(String.self, forKey: .backgroundImage) ?? "benefit_climate"
        self.title = try container.decode(String.self, forKey: .title)
        self.description = try container.decode(String.self, forKey: .description)
        self.badgeText = try container.decode(String.self, forKey: .badgeText)
        self.statusText = try container.decodeIfPresent(String.self, forKey: .statusText) ?? "Aktiv"
        self.isActive = try container.decodeIfPresent(Bool.self, forKey: .isActive) ?? true
        self.cornerRadius = try container.decodeIfPresent(CGFloat.self, forKey: .cornerRadius) ?? 16
    }
}
extension ButtonComponent.Data {
    public enum CodingKeys: String, CodingKey {
        case title = "title"
        case style = "style"
        case isEnabled = "is_enabled"
        case isLoading = "is_loading"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: ButtonComponent.Data.CodingKeys.self)
        self.title = try container.decode(String.self, forKey: .title)
        self.style = try container.decode(ButtonStyle.self, forKey: .style)
        self.isEnabled = try container.decode(Bool.self, forKey: .isEnabled)
        self.isLoading = try container.decode(Bool.self, forKey: .isLoading)
    }
}
extension LanguageSwitcherComponent.Data {
    public enum CodingKeys: String, CodingKey {
        case selectedLanguageCode = "selected_language_code"
        case languageRegions = "language_regions"
        case specificLanguageCodes = "specific_language_codes"
        case showSearch = "show_search"
        case size = "size"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: LanguageSwitcherComponent.Data.CodingKeys.self)
        self.selectedLanguageCode = try container.decodeIfPresent(String.self, forKey: .selectedLanguageCode) ?? "DE"
        self.languageRegions = try container.decodeIfPresent(LanguageRegion.self, forKey: .languageRegions) ?? .all
        self.specificLanguageCodes = try container.decodeIfPresent(Set<String>.self, forKey: .specificLanguageCodes) ?? []
        self.showSearch = try container.decodeIfPresent(Bool.self, forKey: .showSearch) ?? true
        self.size = try container.decodeIfPresent(CGFloat.self, forKey: .size) ?? 32
    }
}
// swiftlint:enable all
