// Auto-generated from priority-packages.json. Do not edit by hand.
// Regenerate via: Scripts/generate-embedded-catalogs.sh

import Foundation

/// JSON content embedded at build time. Replaces the runtime
/// `Bundle.module`/`CupertinoResources.bundle` lookup that failed on
/// Homebrew installs (#161). Updated via PR.
public enum PriorityPackagesEmbedded {
    public static let json: String = #"""
    {
      "version": "1.1",
      "lastUpdated": "2026-04-23",
      "description": "Curated list of high-priority Swift packages (expanded for v0.10.1 recrawl)",
      "tiers": {
        "apple_official": {
          "description": "Critical Apple-maintained Swift packages",
          "owner": "apple",
          "count": 43,
          "packages": [
            { "repo": "sourcekit-lsp", "url": "https://github.com/apple/sourcekit-lsp" },
            { "repo": "swift", "url": "https://github.com/apple/swift" },
            { "repo": "swift-algorithms", "url": "https://github.com/apple/swift-algorithms" },
            { "repo": "swift-argument-parser", "url": "https://github.com/apple/swift-argument-parser" },
            { "repo": "swift-asn1", "url": "https://github.com/apple/swift-asn1" },
            { "repo": "swift-async-algorithms", "url": "https://github.com/apple/swift-async-algorithms" },
            { "repo": "swift-atomics", "url": "https://github.com/apple/swift-atomics" },
            { "repo": "swift-cassandra-client", "url": "https://github.com/apple/swift-cassandra-client" },
            { "repo": "swift-certificates", "url": "https://github.com/apple/swift-certificates" },
            { "repo": "swift-cluster-membership", "url": "https://github.com/apple/swift-cluster-membership" },
            { "repo": "swift-collections", "url": "https://github.com/apple/swift-collections" },
            { "repo": "swift-configuration", "url": "https://github.com/apple/swift-configuration" },
            { "repo": "swift-container-plugin", "url": "https://github.com/apple/swift-container-plugin" },
            { "repo": "swift-crypto", "url": "https://github.com/apple/swift-crypto" },
            { "repo": "swift-distributed-actors", "url": "https://github.com/apple/swift-distributed-actors" },
            { "repo": "swift-distributed-tracing", "url": "https://github.com/apple/swift-distributed-tracing" },
            { "repo": "swift-docc", "url": "https://github.com/apple/swift-docc" },
            { "repo": "swift-driver", "url": "https://github.com/apple/swift-driver" },
            { "repo": "swift-embedded-examples", "url": "https://github.com/apple/swift-embedded-examples" },
            { "repo": "swift-foundation", "url": "https://github.com/apple/swift-foundation" },
            { "repo": "swift-format", "url": "https://github.com/apple/swift-format" },
            { "repo": "swift-homomorphic-encryption", "url": "https://github.com/apple/swift-homomorphic-encryption" },
            { "repo": "swift-http-structured-headers", "url": "https://github.com/apple/swift-http-structured-headers" },
            { "repo": "swift-http-types", "url": "https://github.com/apple/swift-http-types" },
            { "repo": "swift-log", "url": "https://github.com/apple/swift-log" },
            { "repo": "swift-markdown", "url": "https://github.com/apple/swift-markdown" },
            { "repo": "swift-metrics", "url": "https://github.com/apple/swift-metrics" },
            { "repo": "swift-mmio", "url": "https://github.com/apple/swift-mmio" },
            { "repo": "swift-nio", "url": "https://github.com/apple/swift-nio" },
            { "repo": "swift-nio-extras", "url": "https://github.com/apple/swift-nio-extras" },
            { "repo": "swift-nio-http2", "url": "https://github.com/apple/swift-nio-http2" },
            { "repo": "swift-nio-ssh", "url": "https://github.com/apple/swift-nio-ssh" },
            { "repo": "swift-nio-ssl", "url": "https://github.com/apple/swift-nio-ssl" },
            { "repo": "swift-nio-transport-services", "url": "https://github.com/apple/swift-nio-transport-services" },
            { "repo": "swift-numerics", "url": "https://github.com/apple/swift-numerics" },
            { "repo": "swift-openapi-generator", "url": "https://github.com/apple/swift-openapi-generator" },
            { "repo": "swift-openapi-runtime", "url": "https://github.com/apple/swift-openapi-runtime" },
            { "repo": "swift-openapi-urlsession", "url": "https://github.com/apple/swift-openapi-urlsession" },
            { "repo": "swift-package-manager", "url": "https://github.com/apple/swift-package-manager" },
            { "repo": "swift-protobuf", "url": "https://github.com/apple/swift-protobuf" },
            { "repo": "swift-service-context", "url": "https://github.com/apple/swift-service-context" },
            { "repo": "swift-system", "url": "https://github.com/apple/swift-system" },
            { "repo": "swift-testing", "url": "https://github.com/apple/swift-testing" }
          ]
        },
        "ecosystem": {
          "description": "Well-known ecosystem packages: Point-Free, Vapor, Hummingbird, swift-server, swiftlang, tooling, and project-specific seeds from work/g2xi",
          "count": 92,
          "packages": [
            { "owner": "AvdLee", "repo": "Roadmap", "url": "https://github.com/AvdLee/Roadmap" },
            { "owner": "hummingbird-project", "repo": "hummingbird", "url": "https://github.com/hummingbird-project/hummingbird" },
            { "owner": "hummingbird-project", "repo": "hummingbird-auth", "url": "https://github.com/hummingbird-project/hummingbird-auth" },
            { "owner": "hummingbird-project", "repo": "hummingbird-compression", "url": "https://github.com/hummingbird-project/hummingbird-compression" },
            { "owner": "hummingbird-project", "repo": "hummingbird-core", "url": "https://github.com/hummingbird-project/hummingbird-core" },
            { "owner": "hummingbird-project", "repo": "hummingbird-fluent", "url": "https://github.com/hummingbird-project/hummingbird-fluent" },
            { "owner": "hummingbird-project", "repo": "hummingbird-lambda", "url": "https://github.com/hummingbird-project/hummingbird-lambda" },
            { "owner": "hummingbird-project", "repo": "hummingbird-postgres", "url": "https://github.com/hummingbird-project/hummingbird-postgres" },
            { "owner": "hummingbird-project", "repo": "hummingbird-redis", "url": "https://github.com/hummingbird-project/hummingbird-redis" },
            { "owner": "hummingbird-project", "repo": "hummingbird-valkey", "url": "https://github.com/hummingbird-project/hummingbird-valkey" },
            { "owner": "hummingbird-project", "repo": "hummingbird-websocket", "url": "https://github.com/hummingbird-project/hummingbird-websocket" },
            { "owner": "hummingbird-project", "repo": "hummingbird-xct-async-http-client", "url": "https://github.com/hummingbird-project/hummingbird-xct-async-http-client" },
            { "owner": "hummingbird-project", "repo": "postgres-migrations", "url": "https://github.com/hummingbird-project/postgres-migrations" },
            { "owner": "hummingbird-project", "repo": "sse-kit", "url": "https://github.com/hummingbird-project/sse-kit" },
            { "owner": "hummingbird-project", "repo": "swift-jobs", "url": "https://github.com/hummingbird-project/swift-jobs" },
            { "owner": "hummingbird-project", "repo": "swift-jobs-postgres", "url": "https://github.com/hummingbird-project/swift-jobs-postgres" },
            { "owner": "hummingbird-project", "repo": "swift-jobs-valkey", "url": "https://github.com/hummingbird-project/swift-jobs-valkey" },
            { "owner": "hummingbird-project", "repo": "swift-jobs-workflows", "url": "https://github.com/hummingbird-project/swift-jobs-workflows" },
            { "owner": "hummingbird-project", "repo": "swift-mustache", "url": "https://github.com/hummingbird-project/swift-mustache" },
            { "owner": "hummingbird-project", "repo": "swift-mustache-cli", "url": "https://github.com/hummingbird-project/swift-mustache-cli" },
            { "owner": "hummingbird-project", "repo": "swift-openapi-hummingbird", "url": "https://github.com/hummingbird-project/swift-openapi-hummingbird" },
            { "owner": "hummingbird-project", "repo": "swift-websocket", "url": "https://github.com/hummingbird-project/swift-websocket" },
            { "owner": "jpsim", "repo": "Yams", "url": "https://github.com/jpsim/Yams" },
            { "owner": "krzysztofzablocki", "repo": "Inject", "url": "https://github.com/krzysztofzablocki/Inject" },
            { "owner": "krzysztofzablocki", "repo": "KZFileWatchers", "url": "https://github.com/krzysztofzablocki/KZFileWatchers" },
            { "owner": "mattpolzin", "repo": "OpenAPIKit", "url": "https://github.com/mattpolzin/OpenAPIKit" },
            { "owner": "mihaelamj", "repo": "BearerTokenAuthMiddleware", "url": "https://github.com/mihaelamj/BearerTokenAuthMiddleware" },
            { "owner": "mihaelamj", "repo": "OpenAPILoggingMiddleware", "url": "https://github.com/mihaelamj/OpenAPILoggingMiddleware" },
            { "owner": "nicklockwood", "repo": "SwiftFormat", "url": "https://github.com/nicklockwood/SwiftFormat" },
            { "owner": "playbook-ui", "repo": "playbook-ios", "url": "https://github.com/playbook-ui/playbook-ios" },
            { "owner": "pointfreeco", "repo": "combine-schedulers", "url": "https://github.com/pointfreeco/combine-schedulers" },
            { "owner": "pointfreeco", "repo": "swift-case-paths", "url": "https://github.com/pointfreeco/swift-case-paths" },
            { "owner": "pointfreeco", "repo": "swift-clocks", "url": "https://github.com/pointfreeco/swift-clocks" },
            { "owner": "pointfreeco", "repo": "swift-composable-architecture", "url": "https://github.com/pointfreeco/swift-composable-architecture" },
            { "owner": "pointfreeco", "repo": "swift-concurrency-extras", "url": "https://github.com/pointfreeco/swift-concurrency-extras" },
            { "owner": "pointfreeco", "repo": "swift-custom-dump", "url": "https://github.com/pointfreeco/swift-custom-dump" },
            { "owner": "pointfreeco", "repo": "swift-dependencies", "url": "https://github.com/pointfreeco/swift-dependencies" },
            { "owner": "pointfreeco", "repo": "swift-html", "url": "https://github.com/pointfreeco/swift-html" },
            { "owner": "pointfreeco", "repo": "swift-identified-collections", "url": "https://github.com/pointfreeco/swift-identified-collections" },
            { "owner": "pointfreeco", "repo": "swift-issue-reporting", "url": "https://github.com/pointfreeco/swift-issue-reporting" },
            { "owner": "pointfreeco", "repo": "swift-navigation", "url": "https://github.com/pointfreeco/swift-navigation" },
            { "owner": "pointfreeco", "repo": "swift-nonempty", "url": "https://github.com/pointfreeco/swift-nonempty" },
            { "owner": "pointfreeco", "repo": "swift-overture", "url": "https://github.com/pointfreeco/swift-overture" },
            { "owner": "pointfreeco", "repo": "swift-parsing", "url": "https://github.com/pointfreeco/swift-parsing" },
            { "owner": "pointfreeco", "repo": "swift-perception", "url": "https://github.com/pointfreeco/swift-perception" },
            { "owner": "pointfreeco", "repo": "swift-prelude", "url": "https://github.com/pointfreeco/swift-prelude" },
            { "owner": "pointfreeco", "repo": "swift-sharing", "url": "https://github.com/pointfreeco/swift-sharing" },
            { "owner": "pointfreeco", "repo": "swift-snapshot-testing", "url": "https://github.com/pointfreeco/swift-snapshot-testing" },
            { "owner": "pointfreeco", "repo": "swift-tagged", "url": "https://github.com/pointfreeco/swift-tagged" },
            { "owner": "pointfreeco", "repo": "swift-url-routing", "url": "https://github.com/pointfreeco/swift-url-routing" },
            { "owner": "pointfreeco", "repo": "xctest-dynamic-overlay", "url": "https://github.com/pointfreeco/xctest-dynamic-overlay" },
            { "owner": "realm", "repo": "SwiftLint", "url": "https://github.com/realm/SwiftLint" },
            { "owner": "siteline", "repo": "swiftui-introspect", "url": "https://github.com/siteline/swiftui-introspect" },
            { "owner": "soto-project", "repo": "soto", "url": "https://github.com/soto-project/soto" },
            { "owner": "swift-server", "repo": "async-http-client", "url": "https://github.com/swift-server/async-http-client" },
            { "owner": "swift-server", "repo": "swift-openapi-async-http-client", "url": "https://github.com/swift-server/swift-openapi-async-http-client" },
            { "owner": "swift-server", "repo": "swift-openapi-vapor", "url": "https://github.com/swift-server/swift-openapi-vapor" },
            { "owner": "swift-server", "repo": "swift-service-lifecycle", "url": "https://github.com/swift-server/swift-service-lifecycle" },
            { "owner": "swiftlang", "repo": "swift-docc-plugin", "url": "https://github.com/swiftlang/swift-docc-plugin" },
            { "owner": "swiftlang", "repo": "swift-docc-symbolkit", "url": "https://github.com/swiftlang/swift-docc-symbolkit" },
            { "owner": "swiftlang", "repo": "swift-syntax", "url": "https://github.com/swiftlang/swift-syntax" },
            { "owner": "tuist", "repo": "tuist", "url": "https://github.com/tuist/tuist" },
            { "owner": "vapor", "repo": "apns", "url": "https://github.com/vapor/apns" },
            { "owner": "vapor", "repo": "async-kit", "url": "https://github.com/vapor/async-kit" },
            { "owner": "vapor", "repo": "console-kit", "url": "https://github.com/vapor/console-kit" },
            { "owner": "vapor", "repo": "fluent", "url": "https://github.com/vapor/fluent" },
            { "owner": "vapor", "repo": "fluent-kit", "url": "https://github.com/vapor/fluent-kit" },
            { "owner": "vapor", "repo": "fluent-mongo-driver", "url": "https://github.com/vapor/fluent-mongo-driver" },
            { "owner": "vapor", "repo": "fluent-mysql-driver", "url": "https://github.com/vapor/fluent-mysql-driver" },
            { "owner": "vapor", "repo": "fluent-postgres-driver", "url": "https://github.com/vapor/fluent-postgres-driver" },
            { "owner": "vapor", "repo": "fluent-sqlite-driver", "url": "https://github.com/vapor/fluent-sqlite-driver" },
            { "owner": "vapor", "repo": "jwt", "url": "https://github.com/vapor/jwt" },
            { "owner": "vapor", "repo": "jwt-kit", "url": "https://github.com/vapor/jwt-kit" },
            { "owner": "vapor", "repo": "leaf", "url": "https://github.com/vapor/leaf" },
            { "owner": "vapor", "repo": "leaf-kit", "url": "https://github.com/vapor/leaf-kit" },
            { "owner": "vapor", "repo": "multipart-kit", "url": "https://github.com/vapor/multipart-kit" },
            { "owner": "vapor", "repo": "mysql-kit", "url": "https://github.com/vapor/mysql-kit" },
            { "owner": "vapor", "repo": "mysql-nio", "url": "https://github.com/vapor/mysql-nio" },
            { "owner": "vapor", "repo": "postgres-kit", "url": "https://github.com/vapor/postgres-kit" },
            { "owner": "vapor", "repo": "postgres-nio", "url": "https://github.com/vapor/postgres-nio" },
            { "owner": "vapor", "repo": "queues", "url": "https://github.com/vapor/queues" },
            { "owner": "vapor", "repo": "queues-redis-driver", "url": "https://github.com/vapor/queues-redis-driver" },
            { "owner": "vapor", "repo": "redis", "url": "https://github.com/vapor/redis" },
            { "owner": "vapor", "repo": "routing-kit", "url": "https://github.com/vapor/routing-kit" },
            { "owner": "vapor", "repo": "sql-kit", "url": "https://github.com/vapor/sql-kit" },
            { "owner": "vapor", "repo": "sqlite-kit", "url": "https://github.com/vapor/sqlite-kit" },
            { "owner": "vapor", "repo": "sqlite-nio", "url": "https://github.com/vapor/sqlite-nio" },
            { "owner": "vapor", "repo": "swift-getting-started-web-server", "url": "https://github.com/vapor/swift-getting-started-web-server" },
            { "owner": "vapor", "repo": "toolbox", "url": "https://github.com/vapor/toolbox" },
            { "owner": "vapor", "repo": "vapor", "url": "https://github.com/vapor/vapor" },
            { "owner": "vapor", "repo": "websocket-kit", "url": "https://github.com/vapor/websocket-kit" },
            { "owner": "yonaskolb", "repo": "XcodeGen", "url": "https://github.com/yonaskolb/XcodeGen" }
          ]
        }
      },
      "stats": {
        "totalCriticalApplePackages": 43,
        "totalEcosystemPackages": 92,
        "totalPriorityPackages": 135
      }
    }

    """#

    public static var data: Data {
        Data(json.utf8)
    }
}
