// Generated using Sourcery 2.0.2 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
import Foundation

// swiftlint:disable all
// This file is automatically generated by Sourcery

public func registerComponents(in registry: ComponentsRegistry) {
    HelpComponent.register(in: registry)
    SFSymbolComponent.register(in: registry)
    TextComponent.register(in: registry)
}

public func registerDocumentation() {
    ComponentDocumentation.all.append(HelpComponent.documentation)
    ComponentDocumentation.all.append(SFSymbolComponent.documentation)
    ComponentDocumentation.all.append(TextComponent.documentation)
}

// swiftlint:enable all
