// Generated using Sourcery 2.0.2 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
import Foundation

// swiftlint:disable all
// This file is automatically generated by Sourcery

extension HelpComponent {
    public static var documentation: ComponentDocumentation {
        .init(
            name: "HelpComponent",
            kind: HelpComponent.kind,
            variables: [
                .init(
                    name: "kind",
                    type: "String?",
                    documentation: [],
                    defaultValue: ""
                ),
            ]
        )
    }
}
extension SFSymbolComponent {
    public static var documentation: ComponentDocumentation {
        .init(
            name: "SFSymbolComponent",
            kind: SFSymbolComponent.kind,
            variables: [
                .init(
                    name: "systemName",
                    type: "String",
                    documentation: [],
                    defaultValue: ""
                ),
                .init(
                    name: "fontSize",
                    type: "CGFloat",
                    documentation: [],
                    defaultValue: ""
                ),
            ]
        )
    }
}
extension TextComponent {
    public static var documentation: ComponentDocumentation {
        .init(
            name: "TextComponent",
            kind: TextComponent.kind,
            variables: [
                .init(
                    name: "text",
                    type: "String",
                    documentation: [],
                    defaultValue: ""
                ),
                .init(
                    name: "fontSize",
                    type: "CGFloat",
                    documentation: [],
                    defaultValue: "64"
                ),
            ]
        )
    }
}
// swiftlint:enable all
