// Generated using Sourcery 2.0.2 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
import Foundation
// swiftlint:disable all
// This file is automatically generated by Sourcery

extension HelpComponent.Data {
    public enum CodingKeys: String, CodingKey {
        case kind = "kind"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: HelpComponent.Data.CodingKeys.self)
        self.kind = try container.decodeIfPresent(String.self, forKey: .kind) ?? nil
    }
}
extension SFSymbolComponent.Data {
    public enum CodingKeys: String, CodingKey {
        case systemName = "system_name"
        case fontSize = "font_size"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: SFSymbolComponent.Data.CodingKeys.self)
        self.systemName = try container.decode(String.self, forKey: .systemName)
        self.fontSize = try container.decode(CGFloat.self, forKey: .fontSize)
    }
}
extension TextComponent.Data {
    public enum CodingKeys: String, CodingKey {
        case text = "text"
        case fontSize = "font_size"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: TextComponent.Data.CodingKeys.self)
        self.text = try container.decode(String.self, forKey: .text)
        self.fontSize = try container.decodeIfPresent(CGFloat.self, forKey: .fontSize) ?? 64
    }
}
// swiftlint:enable all
